#!/bin/bash
# Set As Wallpaper
# rm -rf $HOME/.cache/SetAsWallpaper/*
# # Copy selected file to temp folder "$HOME/.cache/SetAsWallpaper"
# while [ $# -gt 0 ]; do
#     ORIGINALITEM="$1"    
#     DUPLICATEITEM="${ORIGINALITEM} (copy)"
#     cp -r "$ORIGINALITEM" "$DUPLICATEITEM" $HOME/.cache/SetAsWallpaper/
#     shift
# done
#     mv -f $HOME/.cache/SetAsWallpaper/* $HOME/.cache/SetAsWallpaper/huwallpaper.jpg
# # Make your wallpaper blurry
#     gsettings set org.gnome.desktop.background picture-uri "file:///$HOME/.cache/SetAsWallpaper/huwallpaper.jpg"
#     convert -resize 1440 -quality 100 -brightness-contrast -10x-15 -blur 0x30 $HOME/.cache/SetAsWallpaper/* /usr/share/backgrounds/gdmlock.jpg
# sleep 3
#     gsettings set org.gnome.desktop.screensaver picture-uri "file:///usr/share/backgrounds/gdmlock.jpg"
# # Enjoy!
# exit 1

mkdir -p $HOME/Pictures/.Curr\ Wallpaper
rm -rf $HOME/Pictures/.Curr\ Wallpaper/*
# sh $HOME/.config/i3/run_wal.sh
sleep .5
DUPLICATEITEM="$1 (copy)"
cp $1 ${DUPLICATEITEM} $HOME/Pictures/.Curr\ Wallpaper/
sh $HOME/.config/i3/run_wal.sh 
